### ISSUE TITLE
Feature request: Dropdown menus

### ISSUE THREAD

**Issue by eugenefvdm** [michaeldyrynda/laravel-preset-tailwind#102]
Hi guys please direct me if this isn't a good place to make a feature request.

My opinion is that it would be great to build a dropdown menu for the Tailwind preset. When I first used this preset it wasn't obvious from the screenshots that the menu doesn't drop down like the official Laravel presets. I googled it and found that Adam has created a few videos on how to achieve a dropdown. Honestly having worked with Bootstrap navbar dropdowns before I was quite overwhelmed with the technicalities. It appears highly a bit complicated, and then when you go mobile even more so.

I see even Adam's preset doesn't have the dropdown menu. My opinion is that perhaps if the dropdowns make it to this preset more people will start embracing Tailwind and Laravel.

**Comment by dsalcedo** [comment]
Here you can see one codepen, i use Tailwind and Alpine

https://codepen.io/dsalcedo/pen/bGVKymB

**Comment by benfurfie** [comment]
The preset really isn't the place for this sort of thing. The type of developer that Tailwind is aimed at – and the type that works with it – is one who doesn't really use existing code examples. In fact, adding them would likely result in a net loss of users. I know I'd stop using any preset that included code examples, because it would mean the first thing I need to do is strip out unnecessary code.

**Comment by michaeldyrynda** [comment]
This preset is just helping you get up and running with Tailwind in a fresh Laravel installation, with a basic layout.

If you need dropdowns, you may consider checking out [Tailwind UI](https://tailwindui.com).
