### ISSUE TITLE
TailwindCss Custom Forms

### ISSUE THREAD

**Issue by andreich1980** [michaeldyrynda/laravel-preset-tailwind#83]
What do you think about adding an option to install `tailwindcss/custom-forms` ?
Maybe like this `php artisan preset tailwindcss-auth --custom-forms`
But then you would need to update all the views to use the custom-forms classes...

**Comment by michaeldyrynda** [comment]
I wouldn't make it an option; I'd prefer an all or nothing, otherwise we need to maintain two different versions of the views.

I would, however, prefer to use the custom forms plugin, as that means we don't need to maintain our own version of the classes.

Happy to accept a PR making the change across the forms.

**Comment by andreich1980** [comment]
I guess it could be closed once the PR #84 was merged.
